-- 0. Cleanup (RESET) - COMMENTÉ POUR SÉCURITÉ
-- Décommenter ces lignes seulement si vous voulez vraiment tout effacer et recommencer à zéro
-- DROP TABLE IF EXISTS public.flippers CASCADE;
-- DROP TABLE IF EXISTS public.arcades CASCADE;
-- DROP TABLE IF EXISTS public.others CASCADE;
-- DROP TABLE IF EXISTS public.games CASCADE;

-- 1. Create the single 'games' table (Si elle n'existe pas déjà)
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null, -- 'Flippers', 'Arcade', 'Baby-foot', 'Divers'
  year text,
  description text,
  image_url text,
  status text default 'Disponible',
  price text default 'Sur devis',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security
alter table public.games enable row level security;

-- Policy 1: Public Read (Tout le monde peut voir les jeux)
-- Note: Si la policy existe déjà, cette commande peut échouer, ce n'est pas grave.
drop policy if exists "Enable read access for all users" on public.games; 
create policy "Enable read access for all users"
on public.games for select
to public
using (true);

-- Policy 2: Authenticated Write (Seul l'admin connecté peut modifier)
drop policy if exists "Enable write access for authenticated users" on public.games;
create policy "Enable write access for authenticated users"
on public.games
for all
to authenticated
using (true)
with check (true);

-- 3. Insert initial data (Seed) - COMMENTÉ POUR ÉVITER LES DOUBLONS
-- Décommenter seulement pour une installation fraîche
/*
insert into public.games (title, category, year, description, image_url, status, price)
values
  ('Canada Dry', 'Flippers', '1976', 'Avec son xylophone d’origine, c’est le flipper idéal pour recréer une ambiance vintage années 1970 !', 'https://images.unsplash.com/photo-1599939571322-792a326991f2?q=80', 'Disponible', 'Sur devis'),
  ('F14 Tomcat', 'Flippers', '1987', 'LE flipper Williams mythique des années 80, avec un feed back énorme ! Conçu par Steve Ritchie.', 'https://images.unsplash.com/photo-1698207191191-236746cfdf11?q=80', 'Disponible', 'Sur devis'),
  ('Jurassic Park', 'Flippers', '2019', 'On ne présente plus le film ! Conçu par l''un des meilleurs joueurs au monde, ce flipper possède une profondeur incroyable.', 'https://images.unsplash.com/photo-1616140409059-e9eb7b370126?q=80', 'Disponible', 'Sur devis'),
  ('Borne Arcade 1942', 'Arcade', 'Retro', 'Une vraie borne d''origine Karateco, restaurée et modernisée avec plus de 1000 jeux disponibles !', 'https://images.unsplash.com/photo-1523843268911-45a882919fec?q=80', 'Disponible', 'Sur devis'),
  ('Baby Foot Bonzini', 'Baby-foot', 'Classic', 'Retrouvez le plaisir de faire des "gamelles", "roulettes" et "râteaux" en famille ou entre amis ! Le must des baby foot.', 'https://images.unsplash.com/photo-1628723652899-78c6600c0274?q=80', 'Incontournable', 'Sur devis');
*/
